// <auto-generated />
using System;
using AppProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppProject.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190426102306_Participant_ID")]
    partial class Participant_ID
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppProject.Models.Trainee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AcademicQualification")
                        .IsRequired();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<int?>("BCSBatchNo");

                    b.Property<int>("BatchNo");

                    b.Property<int>("BloodGroup");

                    b.Property<string>("CellNo")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<DateTime>("ClosingDate");

                    b.Property<int>("Course_Name");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("DsheSL");

                    b.Property<int?>("EiinNo");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("EmmergencyContactCellNo")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("EmmergencyContactName")
                        .IsRequired();

                    b.Property<string>("FatherName")
                        .HasMaxLength(100);

                    b.Property<int>("Gender");

                    b.Property<string>("Guid");

                    b.Property<string>("IndexNo")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("LastNaemCourseAttendeded");

                    b.Property<int>("MaritalStatus");

                    b.Property<string>("MotherName")
                        .HasMaxLength(100);

                    b.Property<string>("NID")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("NameOfCadre");

                    b.Property<DateTime>("OpeningDate");

                    b.Property<int?>("ParticipantID");

                    b.Property<string>("PermanentAddress")
                        .IsRequired();

                    b.Property<string>("ProfileImagePath");

                    b.Property<DateTime>("RegDate");

                    b.Property<string>("SignatureImgPath");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("TraineeType");

                    b.Property<string>("WorkplaceAddress")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
